const screens=document.querySelectorAll(".screen"),navigationButtons=document.querySelectorAll("[data-screen]"),bookingForm=document.getElementById("booking-form"),statusText=document.getElementById("form-status"),submitButton=document.getElementById("submit-button"),dateInput=document.getElementById("date");
const EMAILJS_SERVICE_ID="service_w41i3lo",EMAILJS_TEMPLATE_ID="template_0q5mj2y",EMAILJS_PUBLIC_KEY="7BOB9DwXLbs2aEOQl",DEFAULT_ADMIN_EMAIL="timurschule4@gmail.com";
let bookingSettings={pauses:["1. Pause","2. Pause"],weekdays:[1,2,3,4,5],blockedDates:[],maxPerSlot:5,advanceWeeks:8},notificationSettings={enabled:true,email:DEFAULT_ADMIN_EMAIL,subject:"Neuer Streitschlichter-Termin",text:"Ein neuer Termin wurde gebucht."};
function getLocalDateString(date){const offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().split("T")[0]}
function showScreen(id){screens.forEach(s=>{const active=s.id===id;s.hidden=!active;s.classList.toggle("active",active)});navigationButtons.forEach(b=>{const active=b.dataset.screen===id;b.classList.toggle("active",active);active?b.setAttribute("aria-current","page"):b.removeAttribute("aria-current")})}
navigationButtons.forEach(b=>b.addEventListener("click",()=>showScreen(b.dataset.screen)));dateInput.min=getLocalDateString(new Date());
async function notifyAdmin(a){if(!window.emailjs||!notificationSettings.enabled)return false;await emailjs.send(EMAILJS_SERVICE_ID,EMAILJS_TEMPLATE_ID,{admin_email:notificationSettings.email||DEFAULT_ADMIN_EMAIL,name:a.name,klasse:a.klasse,date:a.date,pause:a.pause,email_subject:notificationSettings.subject,email_text:notificationSettings.text},{publicKey:EMAILJS_PUBLIC_KEY});await db.collection("settings").doc("metrics").set({emailCount:firebase.firestore.FieldValue.increment(1),lastEmail:firebase.firestore.FieldValue.serverTimestamp()},{merge:true}).catch(()=>{});return true}
async function loadPublicSettings(){try{const docs=await Promise.all(["booking","notifications","content"].map(id=>db.collection("settings").doc(id).get()));if(docs[0].exists)bookingSettings={...bookingSettings,...docs[0].data()};if(docs[1].exists)notificationSettings={...notificationSettings,...docs[1].data()};if(docs[2].exists){const c=docs[2].data();if(c.room)document.getElementById("public-room").textContent=c.room;if(c.info)document.getElementById("public-info").textContent=c.info;if(c.emergency)document.getElementById("public-emergency").textContent=c.emergency;if(c.team?.length){const box=document.getElementById("public-team");box.replaceChildren(...c.team.map(m=>{const article=document.createElement("article");article.className="team-card";const avatar=document.createElement(m.image?"img":"div");avatar.className="avatar";if(m.image){avatar.src=m.image;avatar.alt=m.name}else avatar.textContent=(m.name||"T")[0];const h=document.createElement("h3");h.textContent=m.name;const p=document.createElement("p");p.textContent=m.role;article.append(avatar,h,p);return article}))}}const pause=document.getElementById("pause");pause.replaceChildren(...bookingSettings.pauses.map(v=>{const o=document.createElement("option");o.value=o.textContent=v;return o}));const max=new Date();max.setDate(max.getDate()+bookingSettings.advanceWeeks*7);dateInput.max=getLocalDateString(max)}catch(e){console.warn("Einstellungen konnten nicht geladen werden:",e)}}
bookingForm.addEventListener("submit",async event=>{event.preventDefault();statusText.className="form-status";if(!bookingForm.reportValidity())return;if(!window.db){statusText.textContent="Die Terminbuchung ist gerade nicht erreichbar.";statusText.classList.add("error");return}const chosen=new Date(`${dateInput.value}T12:00:00`);if(!bookingSettings.weekdays.includes(chosen.getDay())||bookingSettings.blockedDates.includes(dateInput.value)){statusText.textContent="An diesem Tag können keine Termine gebucht werden.";statusText.classList.add("error");return}const data=new FormData(bookingForm),appointment={name:String(data.get("name")).trim(),klasse:String(data.get("klasse")).trim(),date:String(data.get("date")),pause:String(data.get("pause"))};submitButton.disabled=true;submitButton.textContent="Wird gesendet …";try{await db.collection("termine").add(appointment);try{await notifyAdmin(appointment)}catch(e){console.error("E-Mail-Benachrichtigung fehlgeschlagen:",e);await db.collection("settings").doc("metrics").set({lastError:String(e?.text||e?.message||e).slice(0,200)},{merge:true}).catch(()=>{})}bookingForm.reset();dateInput.min=getLocalDateString(new Date());statusText.textContent="Eure Terminanfrage wurde gespeichert. Wir melden uns in der Schule bei euch.";statusText.classList.add("success")}catch(e){console.error("Termin konnte nicht gespeichert werden:",e);statusText.textContent=e?.code==="permission-denied"?"Firebase hat die Buchung abgelehnt. Bitte prüft die Firestore-Regeln.":"Das Speichern hat leider nicht funktioniert.";statusText.classList.add("error")}finally{submitButton.disabled=false;submitButton.textContent="Termin verbindlich anfragen"}});
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js").catch(console.error));loadPublicSettings();
