const languages={
de:["Vertraulich · Fair · Gemeinsam","Streitschlichter","Wir helfen euch, Konflikte ruhig zu klären und gemeinsam eine Lösung zu finden.","Schulwebsite","So unterstützen wir euch","Ein sicherer Ort für faire Gespräche","Bei uns könnt ihr erzählen, was passiert ist. Wir hören allen Seiten zu und helfen euch, eine Lösung zu finden.","Ankommen","Ihr schildert den Konflikt – ohne Unterbrechungen.","Verstehen","Wir klären gemeinsam, was euch wichtig ist.","Lösen","Ihr vereinbart eine faire, konkrete Lösung.","Wichtig:","Bei akuter Gefahr oder Gewalt wendet euch sofort an eine Lehrkraft oder das Sekretariat.","Lernt uns kennen","Euer Streitschlichter-Team","Gespräch vereinbaren","Termin buchen","Füllt die Felder aus. Eure Angaben werden nur zur Organisation des Gesprächs genutzt.","Vor- und Nachname","Klasse","Datum","Zeitraum","Termin verbindlich anfragen","Info","Team","Termin"],
en:["Confidential · Fair · Together","Peer mediators","We help you resolve conflicts calmly and find a solution together.","School website","How we support you","A safe place for fair conversations","Tell us what happened. We listen to everyone and help you find a solution.","Arrive","Describe the conflict without interruptions.","Understand","Together we clarify what matters to you.","Resolve","Agree on a fair and practical solution.","Important:","In case of danger or violence, contact a teacher or the school office immediately.","Meet us","Your mediation team","Arrange a conversation","Book an appointment","Your details are used only to organize the conversation.","First and last name","Class","Date","Break","Request appointment","Info","Team","Appointment"],
ru:["Конфиденциально · Честно · Вместе","Школьные медиаторы","Мы помогаем спокойно разрешать конфликты и вместе находить решение.","Сайт школы","Как мы помогаем","Безопасное место для честного разговора","Расскажите, что произошло. Мы выслушаем всех и поможем найти решение.","Начало","Расскажите о конфликте без перебиваний.","Понимание","Вместе выясним, что для вас важно.","Решение","Договоритесь о справедливом решении.","Важно:","При опасности или насилии сразу обратитесь к учителю или в секретариат.","Познакомьтесь с нами","Ваша команда медиаторов","Договориться о беседе","Записаться","Данные используются только для организации беседы.","Имя и фамилия","Класс","Дата","Перемена","Отправить заявку","Инфо","Команда","Запись"],
uk:["Конфіденційно · Чесно · Разом","Шкільні медіатори","Ми допомагаємо спокійно вирішувати конфлікти та разом знаходити рішення.","Сайт школи","Як ми допомагаємо","Безпечне місце для чесної розмови","Розкажіть, що сталося. Ми вислухаємо всіх і допоможемо знайти рішення.","Початок","Розкажіть про конфлікт без перебивань.","Розуміння","Разом з’ясуємо, що для вас важливо.","Рішення","Домовтеся про справедливе рішення.","Важливо:","У разі небезпеки або насильства негайно зверніться до вчителя чи секретаріату.","Познайомтеся з нами","Ваша команда медіаторів","Домовитися про розмову","Записатися","Дані використовуються лише для організації розмови.","Ім’я та прізвище","Клас","Дата","Перерва","Надіслати заявку","Інфо","Команда","Запис"],
tr:["Gizli · Adil · Birlikte","Akran arabulucuları","Çatışmaları sakin biçimde çözmenize ve birlikte çözüm bulmanıza yardımcı oluyoruz.","Okul sitesi","Size nasıl yardımcı oluyoruz","Adil görüşmeler için güvenli bir yer","Bize ne olduğunu anlatın. Herkesi dinler ve bir çözüm buluruz.","Başlangıç","Çatışmayı sözünüz kesilmeden anlatın.","Anlama","Sizin için neyin önemli olduğunu belirleriz.","Çözüm","Adil bir çözümde anlaşırsınız.","Önemli:","Tehlike veya şiddet durumunda hemen bir öğretmene ya da sekreterliğe başvurun.","Bizimle tanışın","Arabuluculuk ekibiniz","Görüşme ayarla","Randevu al","Bilgileriniz yalnızca görüşmeyi düzenlemek için kullanılır.","Ad ve soyad","Sınıf","Tarih","Teneffüs","Randevu iste","Bilgi","Ekip","Randevu"],
hi:["गोपनीय · निष्पक्ष · साथ मिलकर","सहपाठी मध्यस्थ","हम विवादों को शांति से सुलझाने और मिलकर समाधान खोजने में मदद करते हैं।","स्कूल वेबसाइट","हम कैसे मदद करते हैं","निष्पक्ष बातचीत के लिए सुरक्षित स्थान","हमें बताइए क्या हुआ। हम सभी की बात सुनते हैं और समाधान खोजते हैं।","शुरुआत","बिना रुकावट विवाद के बारे में बताइए।","समझना","हम समझते हैं कि आपके लिए क्या महत्वपूर्ण है।","समाधान","एक निष्पक्ष समाधान पर सहमत हों।","महत्वपूर्ण:","खतरे या हिंसा की स्थिति में तुरंत शिक्षक या स्कूल कार्यालय से संपर्क करें।","हमसे मिलें","आपकी मध्यस्थ टीम","बातचीत तय करें","समय बुक करें","जानकारी केवल बातचीत आयोजित करने के लिए उपयोग होगी।","पूरा नाम","कक्षा","तारीख","अवकाश","समय का अनुरोध करें","जानकारी","टीम","समय"]};
const targets=[".eyebrow",".hero h1",".hero__text",".school-link","#info .section-label","#info-title","#public-info",".steps article:nth-child(1) h3",".steps article:nth-child(1) p",".steps article:nth-child(2) h3",".steps article:nth-child(2) p",".steps article:nth-child(3) h3",".steps article:nth-child(3) p",".notice strong","#public-emergency","#photos .section-label","#photos-title","#termin .section-label","#termin-title","#termin .section-heading>p:last-child","label[for=name]","label[for=klasse]","label[for=date]","label[for=pause]","#submit-button","[data-screen=info]","[data-screen=photos]","[data-screen=termin]"];
const extras={
de:["Zum Inhalt springen","Sprache auswählen","Raum 008","Hier können später Fotos und Namen des aktuellen Teams ergänzt werden.","Schülerteam","Ausgebildete Streitschlichterinnen und Streitschlichter","Begleitung","Unterstützung durch das betreuende Schulteam","1. Pause","2. Pause","z. B. 7b"],
en:["Skip to content","Choose language","Room 008","Photos and names of the current team can be added here.","Student team","Trained peer mediators","Support","Supported by the supervising school team","1st break","2nd break","e.g. 7b"],
ru:["Перейти к содержанию","Выбрать язык","Кабинет 008","Здесь можно добавить фотографии и имена команды.","Команда учеников","Обученные школьные медиаторы","Сопровождение","Поддержка школьной команды","1-я перемена","2-я перемена","например, 7б"],
uk:["Перейти до вмісту","Вибрати мову","Кабінет 008","Тут можна додати фотографії та імена команди.","Команда учнів","Підготовлені шкільні медіатори","Супровід","Підтримка шкільної команди","1-ша перерва","2-га перерва","наприклад, 7б"],
tr:["İçeriğe geç","Dil seç","Oda 008","Güncel ekibin fotoğrafları ve adları buraya eklenebilir.","Öğrenci ekibi","Eğitimli akran arabulucuları","Destek","Sorumlu okul ekibinin desteği","1. teneffüs","2. teneffüs","ör. 7b"],
hi:["मुख्य सामग्री पर जाएँ","भाषा चुनें","कमरा 008","वर्तमान टीम की तस्वीरें और नाम यहाँ जोड़े जा सकते हैं।","छात्र टीम","प्रशिक्षित सहपाठी मध्यस्थ","सहयोग","स्कूल टीम द्वारा सहयोग","पहला अवकाश","दूसरा अवकाश","जैसे 7b"]};
const extraTargets=[".skip-link","label[for=language-select]","#public-room","#photos .section-heading>p:last-child","#public-team article:nth-child(1) h3","#public-team article:nth-child(1) p","#public-team article:nth-child(2) h3","#public-team article:nth-child(2) p"];
const statusTranslations={
en:{"Eure Terminanfrage wurde gespeichert. Wir melden uns in der Schule bei euch.":"Your appointment request was saved. We will contact you at school.","An diesem Tag können keine Termine gebucht werden.":"Appointments cannot be booked on this day.","Das Speichern hat leider nicht funktioniert.":"Unfortunately, saving did not work."},
ru:{"Eure Terminanfrage wurde gespeichert. Wir melden uns in der Schule bei euch.":"Заявка сохранена. Мы свяжемся с вами в школе.","An diesem Tag können keine Termine gebucht werden.":"На этот день запись невозможна.","Das Speichern hat leider nicht funktioniert.":"Не удалось сохранить запись."},
uk:{"Eure Terminanfrage wurde gespeichert. Wir melden uns in der Schule bei euch.":"Заявку збережено. Ми зв’яжемося з вами у школі.","An diesem Tag können keine Termine gebucht werden.":"На цей день запис неможливий.","Das Speichern hat leider nicht funktioniert.":"Не вдалося зберегти запис."},
tr:{"Eure Terminanfrage wurde gespeichert. Wir melden uns in der Schule bei euch.":"Randevu talebiniz kaydedildi. Sizinle okulda iletişime geçeceğiz.","An diesem Tag können keine Termine gebucht werden.":"Bu gün için randevu alınamaz.","Das Speichern hat leider nicht funktioniert.":"Kayıt işlemi başarısız oldu."},
hi:{"Eure Terminanfrage wurde gespeichert. Wir melden uns in der Schule bei euch.":"आपका अनुरोध सहेज लिया गया है। हम स्कूल में आपसे संपर्क करेंगे।","An diesem Tag können keine Termine gebucht werden.":"इस दिन समय बुक नहीं किया जा सकता।","Das Speichern hat leider nicht funktioniert.":"जानकारी सहेजी नहीं जा सकी।"}};
function changeLanguage(code){const words=languages[code]||languages.de;const more=extras[code]||extras.de;targets.forEach((selector,index)=>{const element=document.querySelector(selector);if(!element)return;if(selector==='.school-link')element.childNodes[0].textContent=words[index]+' ';else if(selector.startsWith('[data-screen'))element.lastChild.textContent=words[index];else element.textContent=words[index]});extraTargets.forEach((selector,index)=>{const element=document.querySelector(selector);if(element)element.textContent=more[index]});const pauses=document.querySelectorAll('#pause option');if(pauses[0])pauses[0].textContent=more[8];if(pauses[1])pauses[1].textContent=more[9];document.getElementById('klasse').placeholder=more[10];const picker=document.getElementById('language-select');picker.setAttribute('aria-label',more[1]);document.querySelector('.nav').setAttribute('aria-label',code==='de'?'Hauptnavigation':code==='en'?'Main navigation':'Navigation');document.documentElement.lang=code;picker.value=code;localStorage.setItem('site-language',code)}
document.addEventListener('DOMContentLoaded',()=>{const picker=document.getElementById('language-select');changeLanguage(localStorage.getItem('site-language')||'de');picker.addEventListener('change',()=>changeLanguage(picker.value));new MutationObserver(()=>{const code=picker.value,text=document.getElementById('form-status').textContent;const translated=statusTranslations[code]?.[text];if(translated)document.getElementById('form-status').textContent=translated}).observe(document.getElementById('form-status'),{childList:true})});
