const OWNER_EMAIL = "timurschule4@gmail.com";
const EMAIL_SERVICE = "service_w41i3lo", EMAIL_TEMPLATE = "template_0q5mj2y", EMAIL_KEY = "7BOB9DwXLbs2aEOQl";
let ownerAppointments = [];
const $ = (id) => document.getElementById(id);
const status = (id, text, type="") => { $(id).textContent=text; $(id).className=`form-status ${type}`.trim(); };
const setting = (id) => window.db.collection("settings").doc(id);
const logActivity = (action) => window.db.collection("activities").add({action, at: firebase.firestore.FieldValue.serverTimestamp(), by: window.auth.currentUser?.email || OWNER_EMAIL});

function showOwner(ok){ $("owner-login").classList.toggle("hidden",ok); $("owner-dashboard").classList.toggle("hidden",!ok); $("owner-logout").classList.toggle("hidden",!ok); }
function dateValue(value){ return value?.toDate ? value.toDate() : new Date(value || 0); }
function escapeCsv(v){ return `"${String(v??"").replaceAll('"','""')}"`; }

async function loadAll(){
  const [appointments, admins, activities, booking, email, content, privacy, metrics] = await Promise.all([
    window.db.collection("termine").get(), window.db.collection("admins").get(), window.db.collection("activities").orderBy("at","desc").limit(10).get().catch(()=>({docs:[]})), setting("booking").get(), setting("notifications").get(), setting("content").get(), setting("privacy").get(), setting("metrics").get()
  ]);
  ownerAppointments=appointments.docs.map(d=>({id:d.id,...d.data()}));
  const now=new Date(), monday=new Date(now); monday.setDate(now.getDate()-((now.getDay()+6)%7)); monday.setHours(0,0,0,0); const sunday=new Date(monday); sunday.setDate(monday.getDate()+7);
  $("stat-all").textContent=ownerAppointments.length; $("stat-week").textContent=ownerAppointments.filter(a=>{const d=new Date(a.date+"T12:00:00");return d>=monday&&d<sunday}).length; $("stat-first").textContent=ownerAppointments.filter(a=>a.pause==="1. Pause").length; $("stat-second").textContent=ownerAppointments.filter(a=>a.pause==="2. Pause").length;
  const metricData=metrics.exists?metrics.data():{}; $("stat-mails").textContent=metricData.emailCount||0; $("email-quota").textContent=`${metricData.emailCount||0} / 200`; $("last-email").textContent=metricData.lastEmail?dateValue(metricData.lastEmail).toLocaleString("de-DE"):"–"; $("last-error").textContent=metricData.lastError||"–";
  $("activity-list").replaceChildren(...activities.docs.map(d=>{const p=document.createElement("p");p.textContent=`${d.data().action} · ${dateValue(d.data().at).toLocaleString("de-DE")}`;return p;})); renderAdmins(admins.docs);
  const b=booking.exists?booking.data():{}; $("pauses").value=(b.pauses||["1. Pause","2. Pause"]).join(", "); $("max-per-slot").value=b.maxPerSlot||5; $("advance-weeks").value=b.advanceWeeks||8; $("blocked-dates").value=(b.blockedDates||[]).join(", "); document.querySelectorAll('[name=weekday]').forEach(x=>x.checked=(b.weekdays||[1,2,3,4,5]).includes(Number(x.value)));
  const e=email.exists?email.data():{}; $("email-enabled").checked=e.enabled!==false; $("owner-notification-email").value=e.email||OWNER_EMAIL; $("email-subject").value=e.subject||"Neuer Streitschlichter-Termin"; $("email-text").value=e.text||"Ein neuer Termin wurde gebucht.";
  const c=content.exists?content.data():{}; $("room-text").value=(c.room==="Raum 008"?"Raum 014":c.room)||"Raum 014"; $("info-text").value=c.info||"Hier helfen wir bei Konflikten in der Schule."; $("emergency-text").value=c.emergency||"Bei akuter Gefahr oder Gewalt wendet euch sofort an eine Lehrkraft oder das Sekretariat."; $("team-data").value=(c.team||[]).map(x=>`${x.name} | ${x.role} | ${x.image||""}`).join("\n"); $("retention-days").value=(privacy.exists?privacy.data().retentionDays:90)||90;
  $("firebase-dot").classList.add("ok"); $("firebase-status").textContent="Erreichbar"; $("email-dot").classList.add("ok"); $("email-status").textContent="Konfiguriert"; await cleanupOld(false);
}

function renderAdmins(docs){ const box=$("admin-list"); box.replaceChildren(); docs.forEach(doc=>{const d=doc.data(), row=document.createElement("article");row.className="management-row";row.innerHTML=`<div><strong>${d.email}</strong><small>${d.role} · letzter Login: ${d.lastLogin?dateValue(d.lastLogin).toLocaleString("de-DE"):"noch nie"}</small></div>`;const del=document.createElement("button");del.className="delete-button";del.textContent="Entfernen";del.disabled=d.email===OWNER_EMAIL;del.onclick=async()=>{if(confirm(`${d.email} wirklich entfernen?`)){await doc.ref.delete();await logActivity(`Admin entfernt: ${d.email}`);await loadAll();}};row.append(del);box.append(row);}); }

$("owner-google-login").onclick=()=>window.auth.signInWithPopup(new firebase.auth.GoogleAuthProvider()).catch(e=>status("owner-auth-status",e.message,"error")); $("owner-logout").onclick=()=>window.auth.signOut();
$("admin-form").onsubmit=async e=>{e.preventDefault();const email=$("admin-email").value.trim().toLowerCase();await window.db.collection("admins").doc(email).set({email,role:$("admin-role").value,createdAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});await logActivity(`Admin hinzugefügt: ${email}`);e.target.reset();await loadAll();};
$("booking-settings-form").onsubmit=async e=>{e.preventDefault();await setting("booking").set({pauses:$("pauses").value.split(",").map(x=>x.trim()).filter(Boolean),maxPerSlot:Number($("max-per-slot").value),advanceWeeks:Number($("advance-weeks").value),weekdays:[...document.querySelectorAll('[name=weekday]:checked')].map(x=>Number(x.value)),blockedDates:$("blocked-dates").value.split(",").map(x=>x.trim()).filter(Boolean)});await logActivity("Buchungsregeln geändert");status("booking-settings-status","Gespeichert.","success");};
$("email-settings-form").onsubmit=async e=>{e.preventDefault();await setting("notifications").set({enabled:$("email-enabled").checked,email:$("owner-notification-email").value.trim(),subject:$("email-subject").value.trim(),text:$("email-text").value.trim()});await logActivity("E-Mail-Einstellungen geändert");status("email-settings-status","Gespeichert.","success");};
$("test-email").onclick=async()=>{try{await emailjs.send(EMAIL_SERVICE,EMAIL_TEMPLATE,{admin_email:$("owner-notification-email").value,name:"Test",klasse:"–",date:new Date().toLocaleDateString("de-DE"),pause:"Test",email_subject:$("email-subject").value,email_text:$("email-text").value},{publicKey:EMAIL_KEY});await setting("metrics").set({emailCount:firebase.firestore.FieldValue.increment(1),lastEmail:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});status("email-settings-status","Test-E-Mail wurde gesendet.","success");await loadAll();}catch(e){status("email-settings-status","Test-E-Mail fehlgeschlagen.","error");}};
$("content-form").onsubmit=async e=>{e.preventDefault();const team=$("team-data").value.split("\n").filter(Boolean).map(line=>{const [name,role,image]=line.split("|").map(x=>x.trim());return{name,role,image};});await setting("content").set({room:$("room-text").value,info:$("info-text").value,emergency:$("emergency-text").value,team});await logActivity("Website-Inhalte geändert");status("content-status","Gespeichert.","success");};
async function cleanupOld(report=true){const days=Number($("retention-days").value||90), cutoff=new Date();cutoff.setDate(cutoff.getDate()-days);const old=ownerAppointments.filter(a=>new Date(a.date+"T12:00:00")<cutoff);for(const a of old)await window.db.collection("termine").doc(a.id).delete();if(report)status("privacy-status",`${old.length} alte Termine gelöscht.`,"success");}
$("save-retention").onclick=async()=>{await setting("privacy").set({retentionDays:Number($("retention-days").value)});await cleanupOld();await logActivity("Aufbewahrungsdauer geändert");await loadAll();};
$("csv-export").onclick=()=>{const csv=["Name,Klasse,Datum,Pause",...ownerAppointments.map(a=>[a.name,a.klasse,a.date,a.pause].map(escapeCsv).join(","))].join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv"}));a.download="streitschlichter-termine.csv";a.click();URL.revokeObjectURL(a.href);};
$("delete-all").onclick=async()=>{if(prompt('Zum Löschen aller Termine bitte ALLE LÖSCHEN eingeben:')!=="ALLE LÖSCHEN")return;for(const a of ownerAppointments)await window.db.collection("termine").doc(a.id).delete();await logActivity("Alle Termine gelöscht");status("privacy-status","Alle Termine wurden gelöscht.","success");await loadAll();};

window.addEventListener("load",()=>{if(!window.auth||!window.db){status("owner-auth-status","Firebase konnte nicht geladen werden.","error");return;}window.auth.onAuthStateChanged(async user=>{const isOwner=user?.email?.toLowerCase()===OWNER_EMAIL;showOwner(isOwner);if(user&&!isOwner){status("owner-auth-status","Dieses Konto ist kein Eigentümer.","error");await window.auth.signOut();}if(isOwner){await window.db.collection("admins").doc(OWNER_EMAIL).set({email:OWNER_EMAIL,role:"owner",lastLogin:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});await loadAll();}});});

